import os
import urllib.parse
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

DB_USER = os.getenv("DB_USER",'root')
DB_PASSWORD = urllib.parse.quote_plus(os.getenv("DB_PASSWORD", "Incedo@123"))

DB_HOST = os.getenv("DB_HOST",'localhost')
DB_NAME = os.getenv("DB_NAME",'mydatabase')

DATABASE_URL= f'mysql+mysqlconnector://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}'

# create the database engine
engine = create_engine(DATABASE_URL,echo=True) # echo=True will log all the SQL statements generated by SQLAlchemy
# create a configured "Session" class
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine) 
# autocommit=False means that the session will not automatically commit changes to the database, allowing you to control when changes are saved.
# autoflush=False means that the session will not automatically flush changes to the database, allowing you to control when changes are sent to the database.
# bind=engine means that the session will be bound to the database engine we created earlier.

# create a base class for our models
Base = declarative_base()  #main orm model subclasses have to have to inherit from this